package view;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import util.StringFuncao;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Toshiba
 */
public class ClasseJDialog extends javax.swing.JDialog {

    private Main parent111;
    private int selectedIndex;
    private int cont =1;

    public ClasseJDialog(Main parent, boolean modal) {
        //  super(parent, modal);
        parent111 = parent;
        initComponents();
        setLocationRelativeTo(null);
        setSize(400, 250);
        jTextFieldNomeClasse.setText("Nova Classe "+Main.contador);
        jTextFieldNomeClasse1.setText("NovaClasse"+Main.contador);
    }

    public JButton getjButtonAdicionar() {
        return jButtonAdicionar;
    }

    public JTextField getNomeClasse() {
        return jTextFieldNomeClasse;
    }

    public JTextField getNomeClasse1() {
        return jTextFieldNomeClasse1;
    }

    public JButton getjButtonEditar() {
        return jButtonEditar;
    }

    private boolean camposEmBranco() {
        return jTextFieldNomeClasse1.getText().equals("") || jTextFieldNomeClasse1.getText().equals("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonEditar = new javax.swing.JButton();
        jTextFieldNomeClasse = new javax.swing.JTextField();
        jTextFieldNomeClasse1 = new javax.swing.JTextField();
        jLabelNomeClasse = new javax.swing.JLabel();
        jButtonAdicionar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jTextFieldNomeClasse.setText("Nova Classe 1");
        jTextFieldNomeClasse.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldNomeClasseFocusGained(evt);
            }
        });
        jTextFieldNomeClasse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNomeClasseKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNomeClasseKeyReleased(evt);
            }
        });

        jTextFieldNomeClasse1.setEditable(false);
        jTextFieldNomeClasse1.setText("NovaClasse1");
        jTextFieldNomeClasse1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNomeClasse1KeyReleased(evt);
            }
        });

        jLabelNomeClasse.setText("Nome da classe:");

        jButtonAdicionar.setText("Adicionar");
        jButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarActionPerformed(evt);
            }
        });
        jButtonAdicionar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButtonAdicionarKeyReleased(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jButtonCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButtonCancelarKeyReleased(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "enum", "Embeddable" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelNomeClasse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldNomeClasse1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAdicionar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonEditar)))
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldNomeClasse)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomeClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNomeClasse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldNomeClasse1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonAdicionar)
                        .addComponent(jButtonCancelar))
                    .addComponent(jButtonEditar))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        //parent111.editaClasse(jTextFieldNomeClasse1.getText());
        dispose();
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jTextFieldNomeClasseFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNomeClasseFocusGained
        // TODO add your handling code here:
        jTextFieldNomeClasse.selectAll();
    }//GEN-LAST:event_jTextFieldNomeClasseFocusGained

    private void jTextFieldNomeClasseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomeClasseKeyPressed
        String palavra = jTextFieldNomeClasse.getText();
        palavra = StringFuncao.primeiraMaiuscula(palavra);
        jTextFieldNomeClasse1.setText(palavra);
    }//GEN-LAST:event_jTextFieldNomeClasseKeyPressed

    private void jTextFieldNomeClasseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomeClasseKeyReleased
        String nomeClasse1 = StringFuncao.formataClasse(jTextFieldNomeClasse.getText());
        jTextFieldNomeClasse1.setText(StringFuncao.capitalizaClasse(nomeClasse1));
    }//GEN-LAST:event_jTextFieldNomeClasseKeyReleased

    private void jTextFieldNomeClasse1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomeClasse1KeyReleased

    }//GEN-LAST:event_jTextFieldNomeClasse1KeyReleased

    private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed
       adicionarClasse();
    }//GEN-LAST:event_jButtonAdicionarActionPerformed

    private void jButtonAdicionarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonAdicionarKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonAdicionarKeyReleased

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonCancelarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonCancelarKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonCancelarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JLabel jLabelNomeClasse;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldNomeClasse;
    private javax.swing.JTextField jTextFieldNomeClasse1;
    // End of variables declaration//GEN-END:variables

    void setEdita(int selectedIndex, String s, String s1) {
        this.selectedIndex = selectedIndex;
        jTextFieldNomeClasse.setText(s);
        jTextFieldNomeClasse1.setText(s1);
    }

    private void adicionarClasse() {
        Main.contador++;
         if (!camposEmBranco()) {
             String tipoClasse = "";
             if (jList1.getSelectedIndex()==-1) {
                tipoClasse="class";
             }else{
                  tipoClasse=  jList1.getSelectedValue();
             }
            parent111.addclasses(jTextFieldNomeClasse1.getText(),tipoClasse);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos");
        }
    }
}
